footprint: [[-0.13, -0.18], [-0.13, 0.18], [0.13, 0.18], [0.13, -0.18]] # default is 13 and 18
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 2
publish_frequency: 1 #default 1
transform_tolerance: 1.0

resolution: 0.05

obstacle_range: 3.0 # default 5.5
raytrace_range: 3.5 # 6.0 

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

cost_scaling_factor: 3.0 # 2.8

inflation_g:
    inflation_radius: 1.0 # 0.9
    
inflation_l:
    inflation_radius: 0.20
